// <auto-generated />
using System;
using ESchedulingKoasFKKH.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESchedulingKoasFKKH.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418012319_HapusTanggalSelesai")]
    partial class HapusTanggalSelesai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<int>("StaseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalMulai")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.HasIndex("StaseId");

                    b.ToTable("Jadwal");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PembimbingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PembimbingId");

                    b.ToTable("Kelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.ToTable("Mahasiswa");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pembimbing");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Waktu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stase");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("KelompokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", "Stase")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("StaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");

                    b.Navigation("Stase");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", "Pembimbing")
                        .WithMany("DaftarKelompok")
                        .HasForeignKey("PembimbingId");

                    b.Navigation("Pembimbing");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarMahasiswa")
                        .HasForeignKey("KelompokId");

                    b.Navigation("Kelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Navigation("DaftarJadwal");

                    b.Navigation("DaftarMahasiswa");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Navigation("DaftarKelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Navigation("DaftarJadwal");
                });
#pragma warning restore 612, 618
        }
    }
}
