// <auto-generated />
using System;
using ESchedulingKoasFKKH.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESchedulingKoasFKKH.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420142531_TambahRoleMahasiswaDosenDanPerbaikiSeeding")]
    partial class TambahRoleMahasiswaDosenDanPerbaikiSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pengelola",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "pengelola"
                        },
                        new
                        {
                            Id = 3,
                            Name = "2201001",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "2201002",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "2201003",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 6,
                            Name = "2201004",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "2201005",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "2201006",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 9,
                            Name = "2201007",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 10,
                            Name = "2201008",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 11,
                            Name = "2201009",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 12,
                            Name = "2201010",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 13,
                            Name = "2201011",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 14,
                            Name = "2201012",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 15,
                            Name = "2201013",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 16,
                            Name = "2201014",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "2201015",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 18,
                            Name = "2201016",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 19,
                            Name = "2201017",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 20,
                            Name = "2201018",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 21,
                            Name = "2201019",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 22,
                            Name = "2201020",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "mahasiswa"
                        },
                        new
                        {
                            Id = 23,
                            Name = "198501012010011001",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 24,
                            Name = "198602022011012002",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 25,
                            Name = "197803032009011003",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 26,
                            Name = "198204042012012004",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 27,
                            Name = "197905052010011005",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 28,
                            Name = "198306062013012006",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 29,
                            Name = "197607072008011007",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 30,
                            Name = "198408082014012008",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 31,
                            Name = "197709092007011009",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        },
                        new
                        {
                            Id = 32,
                            Name = "198510102015012010",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "dosen"
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<int>("StaseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalMulai")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.HasIndex("StaseId");

                    b.ToTable("Jadwal");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PembimbingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PembimbingId");

                    b.ToTable("Kelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mahasiswa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NIM = "2201001",
                            Nama = "Ahmad Fauzi",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            NIM = "2201002",
                            Nama = "Siti Nurhaliza",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            NIM = "2201003",
                            Nama = "Muhammad Rizky",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            NIM = "2201004",
                            Nama = "Dewi Anggraini",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            NIM = "2201005",
                            Nama = "Budi Santoso",
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            NIM = "2201006",
                            Nama = "Putri Rahayu",
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            NIM = "2201007",
                            Nama = "Andi Pratama",
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            NIM = "2201008",
                            Nama = "Rina Wati",
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            NIM = "2201009",
                            Nama = "Fajar Nugroho",
                            UserId = 11
                        },
                        new
                        {
                            Id = 10,
                            NIM = "2201010",
                            Nama = "Lestari Dewi",
                            UserId = 12
                        },
                        new
                        {
                            Id = 11,
                            NIM = "2201011",
                            Nama = "Hendra Gunawan",
                            UserId = 13
                        },
                        new
                        {
                            Id = 12,
                            NIM = "2201012",
                            Nama = "Indah Permata",
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            NIM = "2201013",
                            Nama = "Yoga Aditya",
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            NIM = "2201014",
                            Nama = "Nadia Safitri",
                            UserId = 16
                        },
                        new
                        {
                            Id = 15,
                            NIM = "2201015",
                            Nama = "Rizal Ramadhan",
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            NIM = "2201016",
                            Nama = "Fitri Handayani",
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            NIM = "2201017",
                            Nama = "Dimas Ardiansyah",
                            UserId = 19
                        },
                        new
                        {
                            Id = 18,
                            NIM = "2201018",
                            Nama = "Sari Mulyani",
                            UserId = 20
                        },
                        new
                        {
                            Id = 19,
                            NIM = "2201019",
                            Nama = "Agus Setiawan",
                            UserId = 21
                        },
                        new
                        {
                            Id = 20,
                            NIM = "2201020",
                            Nama = "Maya Puspita",
                            UserId = 22
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Pembimbing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NIP = "198501012010011001",
                            Nama = "Drg. Adi Wijaya, Sp.KG",
                            UserId = 23
                        },
                        new
                        {
                            Id = 2,
                            NIP = "198602022011012002",
                            Nama = "Drg. Sinta Maharani, M.Kes",
                            UserId = 24
                        },
                        new
                        {
                            Id = 3,
                            NIP = "197803032009011003",
                            Nama = "Drg. Bambang Hermanto, Sp.BM",
                            UserId = 25
                        },
                        new
                        {
                            Id = 4,
                            NIP = "198204042012012004",
                            Nama = "Drg. Ratna Sari, Sp.Perio",
                            UserId = 26
                        },
                        new
                        {
                            Id = 5,
                            NIP = "197905052010011005",
                            Nama = "Drg. Hasan Basri, Sp.Ort",
                            UserId = 27
                        },
                        new
                        {
                            Id = 6,
                            NIP = "198306062013012006",
                            Nama = "Drg. Anita Kusuma, Sp.PM",
                            UserId = 28
                        },
                        new
                        {
                            Id = 7,
                            NIP = "197607072008011007",
                            Nama = "Drg. Taufik Hidayat, Sp.Pros",
                            UserId = 29
                        },
                        new
                        {
                            Id = 8,
                            NIP = "198408082014012008",
                            Nama = "Drg. Wulandari, M.Sc",
                            UserId = 30
                        },
                        new
                        {
                            Id = 9,
                            NIP = "197709092007011009",
                            Nama = "Drg. Surya Darma, Sp.RKG",
                            UserId = 31
                        },
                        new
                        {
                            Id = 10,
                            NIP = "198510102015012010",
                            Nama = "Drg. Lina Marlina, Sp.KGA",
                            UserId = 32
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Waktu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jenis = 0,
                            Nama = "KODIL",
                            Waktu = 7
                        },
                        new
                        {
                            Id = 2,
                            Jenis = 0,
                            Nama = "PDHK",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 3,
                            Jenis = 0,
                            Nama = "PDHB",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 4,
                            Jenis = 0,
                            Nama = "Bedah dan Teknik Pencitraan Radiologi",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 5,
                            Jenis = 0,
                            Nama = "Kesmavet dan Epidemiologi",
                            Waktu = 4
                        },
                        new
                        {
                            Id = 6,
                            Jenis = 0,
                            Nama = "Kedinasan dan Karantina",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 7,
                            Jenis = 2,
                            Nama = "Seminar",
                            Waktu = 1
                        },
                        new
                        {
                            Id = 8,
                            Jenis = 1,
                            Nama = "Magang Profesi",
                            Waktu = 4
                        },
                        new
                        {
                            Id = 9,
                            Jenis = 1,
                            Nama = "Magang Babi",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 10,
                            Jenis = 1,
                            Nama = "Magang Sapi",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 11,
                            Jenis = 1,
                            Nama = "Magang Satwa Liar",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 12,
                            Jenis = 1,
                            Nama = "Magang Kuda",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 13,
                            Jenis = 3,
                            Nama = "Ujian Komprehensip",
                            Waktu = 1
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("KelompokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", "Stase")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("StaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");

                    b.Navigation("Stase");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", "Pembimbing")
                        .WithMany("DaftarKelompok")
                        .HasForeignKey("PembimbingId");

                    b.Navigation("Pembimbing");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarMahasiswa")
                        .HasForeignKey("KelompokId");

                    b.HasOne("ESchedulingKoasFKKH.Domain.Auth.User", "User")
                        .WithOne("Mahasiswa")
                        .HasForeignKey("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.Auth.User", "User")
                        .WithOne("Pembimbing")
                        .HasForeignKey("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.Auth.User", b =>
                {
                    b.Navigation("Mahasiswa");

                    b.Navigation("Pembimbing");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Navigation("DaftarJadwal");

                    b.Navigation("DaftarMahasiswa");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Navigation("DaftarKelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Navigation("DaftarJadwal");
                });
#pragma warning restore 612, 618
        }
    }
}
