// <auto-generated />
using System;
using ESchedulingKoasFKKH.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESchedulingKoasFKKH.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418044222_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pengelola",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "pengelola"
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<int>("StaseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalMulai")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.HasIndex("StaseId");

                    b.ToTable("Jadwal");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PembimbingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PembimbingId");

                    b.ToTable("Kelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("KelompokId")
                        .HasColumnType("integer");

                    b.Property<string>("NIM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KelompokId");

                    b.ToTable("Mahasiswa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NIM = "2201001",
                            Nama = "Ahmad Fauzi"
                        },
                        new
                        {
                            Id = 2,
                            NIM = "2201002",
                            Nama = "Siti Nurhaliza"
                        },
                        new
                        {
                            Id = 3,
                            NIM = "2201003",
                            Nama = "Muhammad Rizky"
                        },
                        new
                        {
                            Id = 4,
                            NIM = "2201004",
                            Nama = "Dewi Anggraini"
                        },
                        new
                        {
                            Id = 5,
                            NIM = "2201005",
                            Nama = "Budi Santoso"
                        },
                        new
                        {
                            Id = 6,
                            NIM = "2201006",
                            Nama = "Putri Rahayu"
                        },
                        new
                        {
                            Id = 7,
                            NIM = "2201007",
                            Nama = "Andi Pratama"
                        },
                        new
                        {
                            Id = 8,
                            NIM = "2201008",
                            Nama = "Rina Wati"
                        },
                        new
                        {
                            Id = 9,
                            NIM = "2201009",
                            Nama = "Fajar Nugroho"
                        },
                        new
                        {
                            Id = 10,
                            NIM = "2201010",
                            Nama = "Lestari Dewi"
                        },
                        new
                        {
                            Id = 11,
                            NIM = "2201011",
                            Nama = "Hendra Gunawan"
                        },
                        new
                        {
                            Id = 12,
                            NIM = "2201012",
                            Nama = "Indah Permata"
                        },
                        new
                        {
                            Id = 13,
                            NIM = "2201013",
                            Nama = "Yoga Aditya"
                        },
                        new
                        {
                            Id = 14,
                            NIM = "2201014",
                            Nama = "Nadia Safitri"
                        },
                        new
                        {
                            Id = 15,
                            NIM = "2201015",
                            Nama = "Rizal Ramadhan"
                        },
                        new
                        {
                            Id = 16,
                            NIM = "2201016",
                            Nama = "Fitri Handayani"
                        },
                        new
                        {
                            Id = 17,
                            NIM = "2201017",
                            Nama = "Dimas Ardiansyah"
                        },
                        new
                        {
                            Id = 18,
                            NIM = "2201018",
                            Nama = "Sari Mulyani"
                        },
                        new
                        {
                            Id = 19,
                            NIM = "2201019",
                            Nama = "Agus Setiawan"
                        },
                        new
                        {
                            Id = 20,
                            NIM = "2201020",
                            Nama = "Maya Puspita"
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pembimbing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NIP = "198501012010011001",
                            Nama = "Drg. Adi Wijaya, Sp.KG"
                        },
                        new
                        {
                            Id = 2,
                            NIP = "198602022011012002",
                            Nama = "Drg. Sinta Maharani, M.Kes"
                        },
                        new
                        {
                            Id = 3,
                            NIP = "197803032009011003",
                            Nama = "Drg. Bambang Hermanto, Sp.BM"
                        },
                        new
                        {
                            Id = 4,
                            NIP = "198204042012012004",
                            Nama = "Drg. Ratna Sari, Sp.Perio"
                        },
                        new
                        {
                            Id = 5,
                            NIP = "197905052010011005",
                            Nama = "Drg. Hasan Basri, Sp.Ort"
                        },
                        new
                        {
                            Id = 6,
                            NIP = "198306062013012006",
                            Nama = "Drg. Anita Kusuma, Sp.PM"
                        },
                        new
                        {
                            Id = 7,
                            NIP = "197607072008011007",
                            Nama = "Drg. Taufik Hidayat, Sp.Pros"
                        },
                        new
                        {
                            Id = 8,
                            NIP = "198408082014012008",
                            Nama = "Drg. Wulandari, M.Sc"
                        },
                        new
                        {
                            Id = 9,
                            NIP = "197709092007011009",
                            Nama = "Drg. Surya Darma, Sp.RKG"
                        },
                        new
                        {
                            Id = 10,
                            NIP = "198510102015012010",
                            Nama = "Drg. Lina Marlina, Sp.KGA"
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Waktu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jenis = 0,
                            Nama = "KODIL",
                            Waktu = 7
                        },
                        new
                        {
                            Id = 2,
                            Jenis = 0,
                            Nama = "PDHK",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 3,
                            Jenis = 0,
                            Nama = "PDHB",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 4,
                            Jenis = 0,
                            Nama = "Bedah dan Teknik Pencitraan Radiologi",
                            Waktu = 6
                        },
                        new
                        {
                            Id = 5,
                            Jenis = 0,
                            Nama = "Kesmavet dan Epidemiologi",
                            Waktu = 4
                        },
                        new
                        {
                            Id = 6,
                            Jenis = 0,
                            Nama = "Kedinasan dan Karantina",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 7,
                            Jenis = 0,
                            Nama = "Seminar",
                            Waktu = 1
                        },
                        new
                        {
                            Id = 8,
                            Jenis = 1,
                            Nama = "Magang Profesi",
                            Waktu = 4
                        },
                        new
                        {
                            Id = 9,
                            Jenis = 1,
                            Nama = "Magang Babi",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 10,
                            Jenis = 1,
                            Nama = "Magang Sapi",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 11,
                            Jenis = 1,
                            Nama = "Magang Satwa Liar",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 12,
                            Jenis = 1,
                            Nama = "Magang Kuda",
                            Waktu = 2
                        },
                        new
                        {
                            Id = 13,
                            Jenis = 0,
                            Nama = "Ujian Komprehensip",
                            Waktu = 1
                        });
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Jadwal", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("KelompokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", "Stase")
                        .WithMany("DaftarJadwal")
                        .HasForeignKey("StaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelompok");

                    b.Navigation("Stase");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", "Pembimbing")
                        .WithMany("DaftarKelompok")
                        .HasForeignKey("PembimbingId");

                    b.Navigation("Pembimbing");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Mahasiswa", b =>
                {
                    b.HasOne("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", "Kelompok")
                        .WithMany("DaftarMahasiswa")
                        .HasForeignKey("KelompokId");

                    b.Navigation("Kelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Kelompok", b =>
                {
                    b.Navigation("DaftarJadwal");

                    b.Navigation("DaftarMahasiswa");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Pembimbing", b =>
                {
                    b.Navigation("DaftarKelompok");
                });

            modelBuilder.Entity("ESchedulingKoasFKKH.Domain.ModulUtama.Stase", b =>
                {
                    b.Navigation("DaftarJadwal");
                });
#pragma warning restore 612, 618
        }
    }
}
